# Generated by Django 3.2.7 on 2021-09-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library_filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='leads',
            name='Email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Book_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author')),
                ('libraries', models.ManyToManyField(to='book.Library')),
            ],
        ),
    ]
