# Generated by Django 3.2.7 on 2021-09-25 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210924_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_search',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book_search',
            name='libraries',
        ),
        migrations.DeleteModel(
            name='Library_filter',
        ),
        migrations.DeleteModel(
            name='Book_search',
        ),
    ]
